# Generated by Django 5.1 on 2024-09-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
    ]
